name: Cleanup All Workflow Runs

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly at midnight on Sunday

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Delete all workflow runs
        env:
          GH_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
        run: |
          gh run list -L 10000 --json databaseId -q '.[].databaseId' | xargs -I {} gh run delete {}
