name: Purge All Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          workflows=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/workflows" | jq '.workflows[].id')
          
          for workflow in $workflows
          do
            runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/actions/workflows/$workflow/runs" | jq '.workflow_runs[].id')
            
            for run in $runs
            do
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$run"
              echo "Deleted run $run"
            done
          done
